config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq'
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [ENV['ADMIN_LOGIN'], ENV['ADMIN_PASSWORD']]
  end
  mount Sidekiq::Web, at: "/sidekiq"

  root 'home#index'
  post '/webhooks/telegram', controller: 'webhooks', action: 'telegram'
  get '/releases/:id' => 'releases#show', as: 'release'

  namespace :admin do
    get '/' => 'dashboard#index'
    resources :users, only: [:index]
    resources :broadcasts, only: [:new, :create]
    resources :movies, only: [:index]
    resources :searches, only: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/recent.rb
require 'active_support/concern'

module Recent
  extend ActiveSupport::Concern

  included do
    scope :recent, -> (n) { where("created_at >= ?", n.days.ago) }
  end
end

app/models/dashboard.rb
class Dashboard
  def users
    User.count
  end

  def users_delta
    User.recent(7).count
  end

  def movies
    Movie.count
  end

  def movies_delta
    Movie.recent(7).count
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  include Recent

  has_many :releases, dependent: :delete_all
  has_many :wishes, dependent: :delete_all
  has_many :pending_wishes, -> { Wish.pending }, class_name: 'Wish'

  CRAWL_INTERVAL = 24.hours

  scope :ordered, -> { order(crawled_at: :desc) }

  def full_title
    [title, year].compact.join(', ')
  end

  def recently_crawled?
    return false if crawled_at.nil?
    crawled_at > CRAWL_INTERVAL.ago
  end
end

app/models/release.rb
class Release < ApplicationRecord
  belongs_to :movie

  scope :popular, -> { order(:downloads => :desc) }

  def has_link?
    true
  end
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
  belongs_to :movie, optional: true

  enum status: { no_movie: 0, no_releases: 1, error: 2, ok: 3 }

  delegate :id, to: :user, prefix: true
  delegate :full_name, to: :user

  scope :ordered, -> { order(created_at: :desc) }

  def movie_title
    movie.present? ? "#{movie.title}, #{movie.year}" : '-'
  end
end

app/models/user.rb
class User < ApplicationRecord
  DEFAULT_LOCALE = 'en'
  LANGUAGES = {
      'en' => I18n.t('languages.en'),
      'ru' => I18n.t('languages.ru')
  }

  include Recent

  has_many :wishes, dependent: :destroy
  has_many :wanted_movies, through: :wishes, source: :movie
  has_many :searches, dependent: :destroy

  validates :telegram_id, uniqueness: true

  scope :ordered, -> { order("updated_at DESC") }
  scope :active, -> { where(error: 0) }

  enum error: { ok: 0, forbidden: 1 }

  before_validation :set_locale, on: :create

  def message
    @message ||= Telegram::Message.new(telegram_id, locale)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def set_locale
    self.locale = detect_locale || DEFAULT_LOCALE
  end

  def detect_locale
    return if language.nil?
    match = language.match /(\S{2})(-\S{2})?/
    return if match.nil?
    user_language = match[1].downcase
    user_language if LANGUAGES.keys.include?(user_language)
  end
end

app/models/wish.rb
# == Schema Information
#
# Table name: wishes
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  movie_id    :integer
#  notified_at :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Wish < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  scope :pending, -> { where(notified_at: nil) }
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base
  protect_from_forgery with: :exception
  http_basic_authenticate_with name: ENV['ADMIN_LOGIN'], password: ENV['ADMIN_PASSWORD']
  before_action :set_locale

  layout 'admin'

  def set_locale
    I18n.locale = :en
  end
end

app/controllers/admin/broadcasts_controller.rb
class Admin::BroadcastsController < Admin::BaseController
  def new

  end

  def create
    Broadcast.message broadcast_params[:message]

    redirect_to new_admin_broadcast_path, notice: 'Message successfully sent'
  end

  private

  def broadcast_params
    params.permit(:message)
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
    @dashboard = Dashboard.new
  end
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < Admin::BaseController
  def index
    @movies = Movie.ordered.all.includes(:releases).includes(:pending_wishes)
  end
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < Admin::BaseController
  def index

  end

  def collection
    @searches = Search.ordered.all.includes(:user)
  end
  helper_method :collection
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index

  end

  private

  def collection
    @users = User.ordered.all
  end
  helper_method :collection
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  def show
    release = Release.find params[:id]
    @release = Releases::Presenter.new(release)
    @movie = release.movie
  end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ActionController::API

  def telegram
    TelegramChat.dispatch(payload)
    render head: :ok, body: nil
  end

  private

  def payload
    params.permit(:webhook => {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/broadcasts/new.html.erb
<h1>Broadcast</h1>

<%= form_tag admin_broadcasts_path do %>
  <div class="form-group">
      <%= text_area_tag :message, '', class: 'form-control', placeholder: 'Message' %>
  </div>
  <div class="form-group">
    <%=submit_tag 'Send', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/dashboard/index.html.erb
<dl class="row">
  <dt class="col-sm-3"><h4>Users</h4></dt>
  <dd class="col-sm-3"><h4><%=@dashboard.users %></h4></dd>

  <dt class="col-sm-3"><h4>Movies</h4></dt>
  <dd class="col-sm-3"><h4><%=@dashboard.movies %></h4></dd>

  <dt class="col-sm-3"><h4>Users (last week)</h4></dt>
  <dd class="col-sm-3"><h4><%=@dashboard.users_delta %></h4></dd>

  <dt class="col-sm-3"><h4>Movies (last week)</h4></dt>
  <dd class="col-sm-3"><h4><%=@dashboard.movies_delta %><h4></dd>
</dl>

app/views/admin/movies/index.html.erb
<h1>Movies</h1>

<table class="table">
  <tr>
    <th width="10%"></th>
    <th>Title</th>
    <th width="10%">Releases</th>
    <th width="10%">Wish</th>
  </tr>

  <% @movies.each do |movie| %>
  <tr>
    <td><%=image_tag movie.poster, width: '100' unless movie.poster.blank? %></td>
    <td>[<%=movie.id %>] <%=movie.title %> <i>(<%=movie.year%>)</i></td>
    <td><%=movie.releases.size %></td>
    <td><%=movie.pending_wishes.size %></td>
  </tr>
  <% end %>
</table>

app/views/admin/searches/index.html.erb
<h1>Searches</h1>

<table class="table">
  <tr>
    <th width="10%">Status</th>
    <th width="25%">Input</th>
    <th width="25%">Movie</th>
    <th width="20%">User</th>
    <th width="20%">Date</th>
  </tr>
  <% collection.each do |resource| %>
    <tr>
      <td><%= resource.status %></td>
      <td><%= resource.text %></td>
      <td><%= resource.movie_title %></td>
      <td><%= resource.full_name %></td>
      <td><%= time_ago_in_words resource.created_at %> ago</td>
    </tr>
  <% end %>
</table>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<table class="table">
  <tr>
    <th width="5%">Status</th>
    <th width="20%">First</th>
    <th width="20%">Last</th>
    <th width="10%">Language</th>
    <th width="10%">Locale</th>
    <th width="20%">Registered</th>
    <th width="20%">Last Accessed</th>
  </tr>
  <% collection.each do |user| %>
    <tr>
      <td><%= user.error %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.language %></td>
      <td><%= user.locale %></td>
      <td><%= l user.created_at, format: :short %></td>
      <td><%= time_ago_in_words user.updated_at %> ago</td>
    </tr>
  <% end %>
</table>

app/views/home/index.html.erb
<h1>TorrentPanic!</h1>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>TorrentPanic!</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">TorrentPanic!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/admin/">Dashboard <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to 'Searches', admin_searches_url, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Users', admin_users_url, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Movies', admin_movies_url, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Broadcast', new_admin_broadcast_url, class: 'nav-link' %>
      </li>
      <!--<li class="nav-item">-->
        <!--<a class="nav-link disabled" href="#">Disabled</a>-->
      <!--</li>-->
      <!--<li class="nav-item dropdown">-->
        <!--<a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>-->
        <!--<div class="dropdown-menu" aria-labelledby="dropdown01">-->
          <!--<a class="dropdown-item" href="#">Action</a>-->
          <!--<a class="dropdown-item" href="#">Another action</a>-->
          <!--<a class="dropdown-item" href="#">Something else here</a>-->
        <!--</div>-->
      <!--</li>-->
    </ul>
  </div>
</nav>

<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= msg %>
    <% end %>
  <% end %>
</div>

<main role="main" class="container">
  <%= yield %>
</main><!-- /.container -->


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TorrentAlert</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js"></script>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/releases/show.html.erb
<header>
  <h1>TorrentPanic!</h1>
</header>

<div class="movie">
  <img class="movie__poster" src="<%=@movie.poster %>" width="150px">
  <div class="movie__details">
    <h2 class="movie__title"><%=@movie.title %></h2>
    <div class="movie__year"><%=@movie.year%></div>
  </div>
</div>

<div class="panel">
  <h4>Magnet link</h4>

  <div class="release-name"><%=@release.name%></div>

  <div class="input-group">
    <input type="text" value="<%=@release.magnet%>" class="magnet-link input">
    <span class="input-group-button">
      <button class="btn clipboard-btn" data-clipboard-text="<%=@release.magnet%>">
        <img src="<%=image_url('clippy.svg')%>" width="13" alt="copy to clipboard">
      </button>
    </span>
  </div>
</div>

<script>
  function ready(callback) {
    // in case the document is already rendered
    if (document.readyState!='loading') callback();
    // modern browsers
    else if (document.addEventListener) document.addEventListener('DOMContentLoaded', callback);
    // IE <= 8
    else document.attachEvent('onreadystatechange', function(){
      if (document.readyState=='complete') callback();
    });
  }

  ready(function() {
    new Clipboard('.clipboard-btn');
    window.location.href = "<%=@release.magnet %>";
  });
</script>